language: ruby

cache: bundler

rvm:
  - 2.3.7
  - 2.5.1

gemfile:
  - Gemfile
  - test/ci/rails50.gemfile
  - test/ci/rails42.gemfile

matrix:
  exclude:

script:
  - export BUNDLE_PATH=$PWD/vendor/bundle
  - echo $BUNDLE_PATH
  - ls $BUNDLE_PATH
  - bundle exec rake