language: ruby

env:
  global:
    # to be used for dummy and wagons
    - ROOT_BUNDLE_PATH=$PWD/vendor/bundle

cache:
  # cache directory manually instead of bundle to make sure
  # that the $ROOT_BUNDLE_PATH is used correctly.
  directories:
    - $ROOT_BUNDLE_PATH

before_cache: bundle clean

bundler_args: --jobs=3 --retry=3 --path=$ROOT_BUNDLE_PATH

rvm:
  - 2.5.7
  - 2.6.5

# Set as `export BUNDLE_GEMFILE=`pwd`/test/ci/railsXX.gemfile` before running tests
gemfile:
  - Gemfile
  - test/ci/rails52.gemfile

jobs:
  exclude:

