language: ruby

env:
  global:
    # to be used for dummy and wagons
    - ROOT_BUNDLE_PATH=$PWD/vendor/bundle

cache:
  # cache directory manually instead of bundle to make sure
  # that the $ROOT_BUNDLE_PATH is used correctly.
  directories:
    - $ROOT_BUNDLE_PATH

before_cache: bundle clean

bundler_args: --jobs=3 --retry=3 --path=$ROOT_BUNDLE_PATH

rvm:
  - 2.3.7
  - 2.5.1

gemfile:
  - Gemfile
  - test/ci/rails50.gemfile
  - test/ci/rails42.gemfile

matrix:
  exclude:
